repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)

-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate
    -   id: terraform_docs

-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.1.4
    hooks:
    -   id: sqlfluff-lint
        args: [--dialect, redshift]
    -   id: sqlfluff-fix
        args: [--dialect, redshift] 